server:
  port: 8085

spring:
  application:
    name: cloud-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n'

