server:
    port: 8081

eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: false
        fetch-registry: false
#    client:
#        serviceUrl:
#            defaultZone: http://localhost2:8082/eureka/

spring:
    application:
        name: eurka-server
