server:
  port: 8086

spring:
  application:
    name: cloud-operation

eureka:
  client:
    serviceUrl:
      defaultZone:
      http://eureka01.com:7001/eureka/,http://eureka02.com:7002/eureka/,http://eureka03.com:7003/eureka/



#      http://localhost:8081/eureka/